//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGPTruck.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class Credential
    {
        [DataMember]
    public int UserId { get; set; }
        [DataMember]
    public string Hash { get; set; }
        [DataMember]
    public string Salt { get; set; }
        [DataMember]
    public string Token { get; set; }
    
        [DataMember]
    public virtual User User { get; set; }
    }
}
