//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGPTruck.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class User
    {
        [DataMember]
    public int Id { get; set; }
        [DataMember]
    public string Email { get; set; }
        [DataMember]
    public string Name { get; set; }
    
        [DataMember]
    public virtual Credential Credential { get; set; }
    }
}
