//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGPTruck.UWP.Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Failure
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int Vehicule_Id { get; set; }
        public int State { get; set; }
        public int Mission_id { get; set; }
        public Nullable<int> Failure_Detail_Id { get; set; }
        public Nullable<int> Repairer_Id { get; set; }
        public Nullable<int> Repairer_Vehicule_Id { get; set; }
    
        public virtual FailureDetail FailureDetail { get; set; }
        public virtual Mission Mission { get; set; }
        public virtual User Repairer { get; set; }
        public virtual Vehicule RepairerVehicule { get; set; }
        public virtual Vehicule Vehicule { get; set; }
    }
}
