//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGPTruck.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credential
    {
        public int UserId { get; set; }
        public string Hash { get; set; }
        public string Salt { get; set; }
        public string Token { get; set; }
    
        public virtual User User { get; set; }
    }
}
