//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGPTruck.WebAPI.Entities.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CGPTruckEntities : DbContext
    {
        public CGPTruckEntities()
            : base("name=CGPTruckEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<FailureDetail> FailureDetails { get; set; }
        public virtual DbSet<Failure> Failures { get; set; }
        public virtual DbSet<Mission> Missions { get; set; }
        public virtual DbSet<Phone> Phones { get; set; }
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Step> Steps { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vehicule> Vehicules { get; set; }
    }
}
