//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGPTruck.WebAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public int User_Id { get; set; }
        public string Name { get; set; }
        public string Serial_Code { get; set; }
        public PhoneState Phone_State { get; set; }
    
        public virtual User User { get; set; }
    }
}
