//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGPTruck.WebAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Step
    {
        public int Id { get; set; }
        public int StepNumber { get; set; }
        public string Informations { get; set; }
        public int StepType_Id { get; set; }
        public int Mission_Id { get; set; }
    
        public virtual StepType StepType { get; set; }
        public virtual Mission Mission { get; set; }
    }
}
